### ISSUE TITLE
Bible Commentary crashing on Word Docs

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#118]
Example Task id: e4c8b436-69f1-4c6c-a30b-740b6fcbd7b7

This was for ULB and Bible Commentary for Gospel of Mark. It worked fine for PDF and HTML.

**Comment by linearcombination** [comment]
Were you able to test the fix I deployed for Issue #111 which appears to be the same issue?

**Comment by markalolo** [comment]
I tested the deployment that included #111. It worked fine for PDF and HTML but crashed on Word Docs. Would you have preferred that I add this feedback to issue #111?

**Comment by linearcombination** [comment]
I'll have to check Docx again. Perhaps I didn't test it like I thought I did. I'll check and get back to you.

**Comment by markalolo** [comment]
This issue is still crashing on Word Docs in doc-dev. Perhaps the fix didn't deploy yet? The current build on doc-dev is:

Version Information
Build date: 05-02-2023

Git Hash: [f400e32e](https://github.com/WycliffeAssociates/DOC/commits/f400e32e)

**Comment by markalolo** [comment]
I tried English, Matthew, Mark, Luke, John. I included ULB and Commentary. It runs a while and then fails out.

**Comment by markalolo** [comment]
OK, now that the fix is deployed....this is working!

**Comment by markalolo** [comment]
Hi Lang, yes, Dan fixed an issue that prevented deployment. Our infrastructure team moved our datacenter to a new off-site location over the weekend and apparently your pull request came in during that outage, consequently not being processed and deployed. Dan submitted it to run again and now we are up to this point:

https://github.com/WycliffeAssociates/DOC/commits/2652221a

Mark

<><><><><><><><><><>
Mark Stedman
Schedule Time with Me: https://meetme.so/MarkStedman
